# Generated by Django 6.0.4 on 2026-04-21 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('result', models.CharField(max_length=64)),
                ('accuracy', models.FloatField()),
                ('feedback', models.CharField(blank=True, choices=[('', 'No feedback'), ('correct', 'Correct'), ('wrong', 'Wrong')], default='', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
